// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAppMVC.Models;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20240625071204_InitialCreateV2")]
    partial class InitialCreateV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WeatherAppMVC.Models.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cisnienie")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DataPomiaru")
                        .HasColumnType("TEXT");

                    b.Property<string>("GodzinaPomiaru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KierunekWiatru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PredkoscWiatru")
                        .HasColumnType("REAL");

                    b.Property<string>("Stacja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("SumaOpadu")
                        .HasColumnType("REAL");

                    b.Property<float>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<float>("WilgotnoscWzgledna")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WeatherData");
                });
#pragma warning restore 612, 618
        }
    }
}
